/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as MainRouteRouteImport } from './routes/_main/route'
import { Route as MainIndexRouteImport } from './routes/_main/index'
import { Route as MoviesMovieIdRouteImport } from './routes/movies/$movieId'
import { Route as MainDateRouteImport } from './routes/_main/$date'

const PromotionsLazyRouteImport = createFileRoute('/promotions')()
const CinemasLazyRouteImport = createFileRoute('/cinemas')()
const AboutLazyRouteImport = createFileRoute('/about')()

const PromotionsLazyRoute = PromotionsLazyRouteImport.update({
  id: '/promotions',
  path: '/promotions',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/promotions.lazy').then((d) => d.Route))
const CinemasLazyRoute = CinemasLazyRouteImport.update({
  id: '/cinemas',
  path: '/cinemas',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/cinemas.lazy').then((d) => d.Route))
const AboutLazyRoute = AboutLazyRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/about.lazy').then((d) => d.Route))
const MainRouteRoute = MainRouteRouteImport.update({
  id: '/_main',
  getParentRoute: () => rootRouteImport,
} as any)
const MainIndexRoute = MainIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MainRouteRoute,
} as any)
const MoviesMovieIdRoute = MoviesMovieIdRouteImport.update({
  id: '/movies/$movieId',
  path: '/movies/$movieId',
  getParentRoute: () => rootRouteImport,
} as any)
const MainDateRoute = MainDateRouteImport.update({
  id: '/$date',
  path: '/$date',
  getParentRoute: () => MainRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof MainIndexRoute
  '/about': typeof AboutLazyRoute
  '/cinemas': typeof CinemasLazyRoute
  '/promotions': typeof PromotionsLazyRoute
  '/$date': typeof MainDateRoute
  '/movies/$movieId': typeof MoviesMovieIdRoute
}
export interface FileRoutesByTo {
  '/about': typeof AboutLazyRoute
  '/cinemas': typeof CinemasLazyRoute
  '/promotions': typeof PromotionsLazyRoute
  '/$date': typeof MainDateRoute
  '/movies/$movieId': typeof MoviesMovieIdRoute
  '/': typeof MainIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_main': typeof MainRouteRouteWithChildren
  '/about': typeof AboutLazyRoute
  '/cinemas': typeof CinemasLazyRoute
  '/promotions': typeof PromotionsLazyRoute
  '/_main/$date': typeof MainDateRoute
  '/movies/$movieId': typeof MoviesMovieIdRoute
  '/_main/': typeof MainIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/cinemas'
    | '/promotions'
    | '/$date'
    | '/movies/$movieId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/about'
    | '/cinemas'
    | '/promotions'
    | '/$date'
    | '/movies/$movieId'
    | '/'
  id:
    | '__root__'
    | '/_main'
    | '/about'
    | '/cinemas'
    | '/promotions'
    | '/_main/$date'
    | '/movies/$movieId'
    | '/_main/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  MainRouteRoute: typeof MainRouteRouteWithChildren
  AboutLazyRoute: typeof AboutLazyRoute
  CinemasLazyRoute: typeof CinemasLazyRoute
  PromotionsLazyRoute: typeof PromotionsLazyRoute
  MoviesMovieIdRoute: typeof MoviesMovieIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/promotions': {
      id: '/promotions'
      path: '/promotions'
      fullPath: '/promotions'
      preLoaderRoute: typeof PromotionsLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cinemas': {
      id: '/cinemas'
      path: '/cinemas'
      fullPath: '/cinemas'
      preLoaderRoute: typeof CinemasLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_main': {
      id: '/_main'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof MainRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_main/': {
      id: '/_main/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof MainIndexRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/movies/$movieId': {
      id: '/movies/$movieId'
      path: '/movies/$movieId'
      fullPath: '/movies/$movieId'
      preLoaderRoute: typeof MoviesMovieIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_main/$date': {
      id: '/_main/$date'
      path: '/$date'
      fullPath: '/$date'
      preLoaderRoute: typeof MainDateRouteImport
      parentRoute: typeof MainRouteRoute
    }
  }
}

interface MainRouteRouteChildren {
  MainDateRoute: typeof MainDateRoute
  MainIndexRoute: typeof MainIndexRoute
}

const MainRouteRouteChildren: MainRouteRouteChildren = {
  MainDateRoute: MainDateRoute,
  MainIndexRoute: MainIndexRoute,
}

const MainRouteRouteWithChildren = MainRouteRoute._addFileChildren(
  MainRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  MainRouteRoute: MainRouteRouteWithChildren,
  AboutLazyRoute: AboutLazyRoute,
  CinemasLazyRoute: CinemasLazyRoute,
  PromotionsLazyRoute: PromotionsLazyRoute,
  MoviesMovieIdRoute: MoviesMovieIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
